/** Catalog: Indian & international authors with Open Library cover URLs */

export function coverFromIsbn(isbn: string) {
  const clean = isbn.replace(/-/g, "");
  return `https://covers.openlibrary.org/b/isbn/${clean}-M.jpg?default=false`;
}

/** Default INR prices by category (Indian market) */
export function priceInrForCategory(categorySlug: string, title: string): number {
  const prices: Record<string, number> = {
    "computer-science": 899,
    "indian-literature": 350,
    "international-classics": 450,
    fiction: 499,
    business: 550,
    science: 599,
    "self-help": 399,
    "history-biography": 425,
  };
  const base = prices[categorySlug] ?? 399;
  // Slight variation by title length for realism
  return base + (title.length % 5) * 20;
}

export const categories = [
  { name: "Computer Science", slug: "computer-science" },
  { name: "Fiction", slug: "fiction" },
  { name: "Indian Literature", slug: "indian-literature" },
  { name: "International Classics", slug: "international-classics" },
  { name: "Business", slug: "business" },
  { name: "Science", slug: "science" },
  { name: "Self Help", slug: "self-help" },
  { name: "History & Biography", slug: "history-biography" },
];

export const books = [
  // —— Computer Science ——
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "9780132350884",
    description: "A handbook of agile software craftsmanship for professional developers.",
    categorySlug: "computer-science",
    publishedYear: 2008,
  },
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    isbn: "9780262033848",
    description: "The definitive guide to algorithms and data structures used worldwide.",
    categorySlug: "computer-science",
    publishedYear: 2009,
  },
  {
    title: "Python Crash Course",
    author: "Eric Matthes",
    isbn: "9781593279288",
    description: "A hands-on, project-based introduction to Python programming.",
    categorySlug: "computer-science",
    publishedYear: 2019,
  },
  {
    title: "Hands-On Machine Learning",
    author: "Aurélien Géron",
    isbn: "9781098125974",
    description: "Concepts, tools, and techniques to build intelligent systems with Scikit-Learn and TensorFlow.",
    categorySlug: "computer-science",
    publishedYear: 2022,
  },
  {
    title: "The Pragmatic Programmer",
    author: "David Thomas, Andrew Hunt",
    isbn: "9780135957059",
    description: "Your journey to mastery in software development.",
    categorySlug: "computer-science",
    publishedYear: 2019,
  },
  // —— Indian Literature ——
  {
    title: "The Guide",
    author: "R.K. Narayan",
    isbn: "9780143039648",
    description: "A classic Indian novel about a tour guide who becomes a spiritual leader.",
    categorySlug: "indian-literature",
    publishedYear: 1958,
  },
  {
    title: "Midnight's Children",
    author: "Salman Rushdie",
    isbn: "9780099578512",
    description: "Magical realism tracing India's independence through the life of Saleem Sinai.",
    categorySlug: "indian-literature",
    publishedYear: 1981,
  },
  {
    title: "The God of Small Things",
    author: "Arundhati Roy",
    isbn: "9780006550686",
    description: "Man Booker Prize winner set in Kerala — family, love, and social hierarchy.",
    categorySlug: "indian-literature",
    publishedYear: 1997,
  },
  {
    title: "A Suitable Boy",
    author: "Vikram Seth",
    isbn: "9780060930347",
    description: "Epic novel of post-independence India — politics, family, and romance.",
    categorySlug: "indian-literature",
    publishedYear: 1993,
  },
  {
    title: "Five Point Someone",
    author: "Chetan Bhagat",
    isbn: "9788129105290",
    description: "Story of three friends at IIT Delhi — humor, friendship, and academic pressure.",
    categorySlug: "indian-literature",
    publishedYear: 2004,
  },
  {
    title: "The Immortals of Meluha",
    author: "Amish Tripathi",
    isbn: "9789380658747",
    description: "Shiva trilogy — mythological fiction reimagining Lord Shiva as a mortal hero.",
    categorySlug: "indian-literature",
    publishedYear: 2010,
  },
  {
    title: "The Blue Umbrella",
    author: "Ruskin Bond",
    isbn: "9780143331987",
    description: "Beloved children's novella set in the hills of Garhwal.",
    categorySlug: "indian-literature",
    publishedYear: 1980,
  },
  {
    title: "Godaan",
    author: "Munshi Premchand",
    isbn: "9788170283551",
    description: "Hindi literary classic on rural poverty and the gift of a cow.",
    categorySlug: "indian-literature",
    publishedYear: 1936,
  },
  {
    title: "Train to Pakistan",
    author: "Khushwant Singh",
    isbn: "9780802142215",
    description: "Powerful novel of Partition and communal violence in a Punjab village.",
    categorySlug: "indian-literature",
    publishedYear: 1956,
  },
  {
    title: "The White Tiger",
    author: "Aravind Adiga",
    isbn: "9781416562603",
    description: "Man Booker winner — darkly comic tale of class struggle in modern India.",
    categorySlug: "indian-literature",
    publishedYear: 2008,
  },
  {
    title: "Ignited Minds",
    author: "A.P.J. Abdul Kalam",
    isbn: "9780143029823",
    description: "Vision for a developed India by the beloved scientist-president.",
    categorySlug: "indian-literature",
    publishedYear: 2002,
  },
  {
    title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    isbn: "9788173711465",
    description: "Autobiography of India's missile man — from Rameswaram to Rashtrapati Bhavan.",
    categorySlug: "history-biography",
    publishedYear: 1999,
  },
  // —— International Classics & Fiction ——
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    isbn: "9780747532699",
    description: "A young wizard discovers his magical heritage at Hogwarts.",
    categorySlug: "fiction",
    publishedYear: 1997,
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    isbn: "9780261102385",
    description: "Epic fantasy — the fellowship's quest to destroy the One Ring.",
    categorySlug: "international-classics",
    publishedYear: 1954,
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    description: "Dystopian masterpiece on totalitarianism, surveillance, and thought control.",
    categorySlug: "international-classics",
    publishedYear: 1949,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9780141439518",
    description: "Romantic classic of manners — Elizabeth Bennet and Mr. Darcy.",
    categorySlug: "international-classics",
    publishedYear: 1813,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    description: "American classic on racial injustice in the Deep South.",
    categorySlug: "international-classics",
    publishedYear: 1960,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    description: "Jazz Age tragedy of wealth, love, and the American Dream.",
    categorySlug: "international-classics",
    publishedYear: 1925,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    description: "A shepherd's journey to find his Personal Legend.",
    categorySlug: "fiction",
    publishedYear: 1988,
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    isbn: "9781594480003",
    description: "Friendship and redemption set against Afghanistan's turbulent history.",
    categorySlug: "fiction",
    publishedYear: 2003,
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    description: "A brief history of humankind — from Stone Age to the present.",
    categorySlug: "history-biography",
    publishedYear: 2011,
  },
  // —— Business ——
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "9780307887894",
    description: "How today's entrepreneurs build successful startups through validated learning.",
    categorySlug: "business",
    publishedYear: 2011,
  },
  {
    title: "Zero to One",
    author: "Peter Thiel",
    isbn: "9780804139298",
    description: "Notes on startups, or how to build the future.",
    categorySlug: "business",
    publishedYear: 2014,
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    isbn: "9781612680194",
    description: "What the rich teach their kids about money that the poor do not.",
    categorySlug: "business",
    publishedYear: 1997,
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    isbn: "9781585424337",
    description: "Timeless principles of personal achievement and wealth building.",
    categorySlug: "business",
    publishedYear: 1937,
  },
  // —— Science & Self Help ——
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "9780553380163",
    description: "From the Big Bang to black holes — cosmology for everyone.",
    categorySlug: "science",
    publishedYear: 1988,
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    description: "An easy and proven way to build good habits and break bad ones.",
    categorySlug: "self-help",
    publishedYear: 2018,
  },
  {
    title: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    isbn: "9788172345668",
    description: "Unlock the hidden power of your mind for success and happiness.",
    categorySlug: "self-help",
    publishedYear: 1963,
  },
  {
    title: "Ikigai",
    author: "Héctor García, Francesc Miralles",
    isbn: "9781523501967",
    description: "The Japanese secret to a long and happy life.",
    categorySlug: "self-help",
    publishedYear: 2016,
  },
];
